### ISSUE TITLE
Importing OpenCV alongside D3DShot results in COMError at create()

### ISSUE THREAD

**Issue by UsaidPro** [SerpentAI/D3DShot#4] opened 2019-07-30 11:22 UTC
Hello,

I have run into a peculiar issue using this library (thanks for creating this btw!). When I try to import OpenCV (cv2 package) I run into this error at `d3dshot.create()`:
```
(-2005270524, 'The specified device interface or feature level is not supported on this system.', (None, None, None, 0, None))
```
Here is my current code:
```
import d3dshot
import time
import cv2
d = d3dshot.create() #Error happens here
```
Removing the `import cv2` line lets the code run without any errors. I have tried running the code as Administrator with same results.

This issue isn't urgent at all (I just wanted OpenCV for rendering, so I found a workaround) and seems to be a niche case, but I still wanted to leave this issue here in case others had similar issues.

**Comment by nbrochu** [comment] 2019-08-13 16:25
This is indeed peculiar. For what it's worth, I can't reproduce it on my end.

![Annotation 2019-08-13 120849 PNG](https://user-images.githubusercontent.com/35039/62957603-23e51980-bdc3-11e9-984a-83cbb54a28ac.jpg)

This is with `opencv-python==4.1.0.25` and `D3DShot==0.1.3` on Windows 10 64 bit.

The error message you are getting essentially means that it's impossible to create a DirectX 11 Device that can do desktop duplication with the loaded DLLs. Your system DLLs are clearly fine since it all works without OpenCV. 

My wild guess: OpenCV has its own capture routines and on Windows it does so by hooking into Direct3D using a shim DLL that doesn't have the feature level required to create a DirectX 11 Device that can do desktop duplication (i.e. it's an older DLL than the system one). When I bootstrap D3DShot, If the shim is loaded, the `ctypes` module finds that instead when I request a DLL by name.

What version of OpenCV are you using? How was it built? If you didn't compile it, are you using the most appropriate wheel for your system? Just trying to think of reasons why it works on my system and not yours.

**Comment by nbrochu** [comment] 2020-05-28 01:34
Any update on this? I don't want to close the issue because there is definitely something interesting lying here but I can't reproduce it as shown above.

**Comment by UsaidPro** [comment] 2020-05-28 04:07
It has been so long that I do not recall if I solved the issue before halting my project. I have plans to continue working on my project that uses both OpenCV and D3DShot later this year (and might rerun into the issue). So I guess this issue can be closed and I will comment on this issue if I run into the same error again later.

**Comment by nbrochu** [comment] 2020-05-28 07:58
Alright, I will close it, but do reopen if you encounter it again. Thanks

**Closed as completed by nbrochu** 2020-05-28 07:58 UTC
Labels: bug, help wanted
