### ISSUE TITLE
Getting garbled image on screenshot

### ISSUE THREAD

**Issue by Maheidem** [SerpentAI/D3DShot#19] opened 2020-02-20 14:44 UTC
Hi,

I´ve been trying to use D3DShot but it´s been returning a garbled image, like this:

I´m thinking this has something to do with drivers, any thoughts?

**Comment by venusjoel** [comment] 2020-02-28 21:29
I am experiencing the same issue, did you come up with a solution?

**Comment by Maheidem** [comment] 2020-02-29 12:05
So far nothing. I haven't actually tried any more. Easier to just find some other solution

**Comment by Disablez** [comment] 2020-04-06 20:57
On an nvidia 2080 Ti it happens at 3440x1440 resolution; lowering it fixes the problem, but obviously it's just a temporary workaround.
Tried all capture methods... pil, numpy, torch_gpu ... etc, same result.

**Comment by nbrochu** [comment] 2020-05-28 09:42
Apologies for the late reply.

For everyone getting the garbled images, can you share a snippet of what you do with the output you get from D3DShot? Do you pass it to scikit-image, OpenCV, Pillow, Other?

Information about OS, Python, Resolution, GPUs is also useful.

I'd love to get this fixed but will need some examples to find a first clue.

**Comment by nbrochu** [comment] 2020-05-28 09:56
Possible hint in #11 

For maximum performance, the buffer at the pointer returned by the Desktop Duplication API is left as is. NumPy is able to perform view manipulations to access the buffer differently without altering it. It's possible that whatever you pass your D3DShot output to tries to access the raw buffer of the array instead of its view. That would cause garbled images because the shape and stride information would be lost.

That wouldn't explain why @Ricky54326 only sees a garbled image at very high resolutions and it works otherwise though. Maybe the array is getting copied at some point? That forces an ordering of the new buffer to conform to the view.

**Comment by gbrlfaria** [comment] 2020-05-28 17:29
Here's my attempt to reproduce the issue. I have tested d3dshot with two code snippets.

The first one uses the "numpy" output format and displays the image using OpenCV.
```py
import cv2
import d3dshot

d = d3dshot.create(capture_output='numpy')
img = d.screenshot()

cv2.imshow('screenshot', img)
cv2.waitKey()
```
The second one uses the default capture output format (PIL) and just saves the screenshot to disk.
```py
import d3dshot

d = d3dshot.create()
img = d.screenshot_to_disk()
```
In both cases, the output image is garbled and looks like [this](https://i.imgur.com/GFRqmuJ.png) (it should be a Visual Studio Code window). Although I didn't test other output formats like @Disablez did, I am positive that the same problem happens.

Now some information about the environment in which I performed the tests above.
```
Operating System: Windows 10 Home Edition, version 1909 (build 18363.836)
Python Version: Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Resolution: 1366x768
GPU (integrated): Intel(R) HD Graphics 620 (python.exe was run with this graphics card)
GPU (discrete): NVIDIA GeForce 920MX
```
And this is the output for `d.displays`.
```
[<Display name=Generic PnP Monitor adapter=Intel(R) HD Graphics 620 resolution=1366x768 rotation=0 scale_factor=1.0 primary=True>]
```

**Edit:**
I have just tested the same code with the same environment, except that I lowered the desktop resolution to **1360x768** and it works just fine. Actually, it works for any value lower than 1366x768. Maybe the issue happens only when the desktop is set to the maximum resolution?

**Comment by j4hangir** [comment] 2020-06-10 19:32
I made a duplicate of this issue here https://github.com/SerpentAI/D3DShot/issues/26, seems there hasn't be a solution yet...

**Comment by nbrochu** [comment] 2020-06-10 19:38
Doing a D3DShot day tomorrow. I'm going to be trying to reproduce this. Seems like it's pretty widespread too.

**Comment by j4hangir** [comment] 2020-06-10 23:04
> Doing a D3DShot day tomorrow. I'm going to be trying to reproduce this. Seems like it's pretty widespread too.

I tinkered around a bit. My observation is that the scrshots look as-if the screen is pixels are moving very fast from left to right, therefore all the pixels drag a little rightwards, similar to a fast car speeding away.

How that'd be of help is not clear, but if lowering the resolution works - I didn't test - maybe could be that the buffer is being overwritten as a `frame` is returned, being a result of too much to chew too quickly.

**Comment by nbrochu** [comment] 2020-06-11 21:29
It would appear the issue is only present with certain resolutions. I finally managed to get garbled output by forcing resolutions in the Nvidia Control Panel.

Here are my results:

* **2560 x 1440**: OK
* **2160 x 1200**: Garbled
* **1920 x 1440**: OK
* **1920 x 1200**: OK
* **1920 x 1080**: OK
* **1768 x 992**: Garbled
* **1680 x 1050**: Garbled
* **1600 x 1200**: OK
* **1600 x 1024**: OK
* **1600 x 900**: OK
* **1366 x 768**: Garbled  (matches @gabriel-dev)
* **1360 x 768**: Garbled  (doesn't match @gabriel-dev)
* **1280 x 1024**: OK
* **1280 x 960**: OK
* **1280 x 800**: OK
* **1280 x 768**: OK
* **1280 x 720**: OK
* **1152 x 864**: OK
* **1024 x 768**: OK
* **800 x 600**: OK

Now to figure out what's happening at those resolutions...

**Comment by nbrochu** [comment] 2020-06-11 22:15
I believe I have found the source of the problem. At the _garbled_ resolutions, the pitch of the `DXGI_MAPPED_RECT` doesn't match `width * 4`.

Example:
* 2560 x 1440 => DXGI_MAPPED_RECT.Pitch = 10240 = 2560 * 4 = Not Garbled
* 2160 x 1200 => DXGI_MAPPED_RECT.Pitch = 8704 != 2160 * 4 = Garbled

If I don't respect the pitch given by the `IDXGISurface`, I start filling in the next row of pixels while still in the potential padding from the previous row. This causes the row offset or garbled effect in the screenshot you all shared.

Windows seems to pad the `IDXGISurface` so the width will be divisible by 32. This is probably to enable all the neat tricks you can do with strides. If you check carefully in my resolution tests above, all the ones that are garbled don't have widths that are divisible by 32.

Fix on the way!

**Comment by nbrochu** [comment] 2020-06-12 00:17
Happy to report that the issue is now fixed. Be sure to grab _D3DShot_ 0.1.5 and let me know how it goes.

**Closed as completed by nbrochu** 2020-06-12 00:17 UTC
Labels: bug, help wanted

**Comment by Arcitec** [comment] 2020-09-26 01:55
Very cool. Great bug hunting and conclusion, @nbrochu ! :-)
